DROP SCHEMA IF EXISTS BRAIN_AGRICULTURE CASCADE;
CREATE SCHEMA IF NOT EXISTS BRAIN_AGRICULTURE;

--CREATE SEQUENCES
CREATE SEQUENCE BRAIN_AGRICULTURE.DOCUMENT_TYPE_ID_SEQ;
CREATE SEQUENCE BRAIN_AGRICULTURE.PLANTED_CROPS_ID_SEQ;
CREATE SEQUENCE BRAIN_AGRICULTURE.PRODUCER_ID_SEQ;
CREATE SEQUENCE BRAIN_AGRICULTURE.PRODUCER_PLANTED_CROPS_ID_SEQ;

CREATE TABLE BRAIN_AGRICULTURE.DOCUMENT_TYPE (
    DOCUMENT_TYPE_ID INT DEFAULT nextval('BRAIN_AGRICULTURE.DOCUMENT_TYPE_ID_SEQ') NOT NULL,
    DOCUMENT_NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (DOCUMENT_TYPE_ID),
    CONSTRAINT UQ_DOC_NAME UNIQUE (DOCUMENT_NAME)
);

INSERT INTO BRAIN_AGRICULTURE.DOCUMENT_TYPE (DOCUMENT_NAME) VALUES 
('CPF'),
('CNPJ');

CREATE TABLE BRAIN_AGRICULTURE.PLANTED_CROPS (
    PLANTED_CROP_ID INT DEFAULT nextval('BRAIN_AGRICULTURE.PLANTED_CROPS_ID_SEQ') NOT NULL,
    PLANTED_CROP_NAME VARCHAR(80) NOT NULL,
    PRIMARY KEY (PLANTED_CROP_ID),
    CONSTRAINT UQ_PLANTED_CROP_NAME UNIQUE (PLANTED_CROP_NAME)
);

INSERT INTO BRAIN_AGRICULTURE.PLANTED_CROPS (PLANTED_CROP_NAME) VALUES
('Soja'),
('Milho');

CREATE TABLE BRAIN_AGRICULTURE.PRODUCER (
    PRODUCER_ID INT DEFAULT nextval('BRAIN_AGRICULTURE.PRODUCER_ID_SEQ') NOT NULL,
    DOCUMENT_TYPE_ID INT NOT NULL,
    DOCUMENT_NUMBER VARCHAR(20) NOT NULL,
    PRODUCER_NAME VARCHAR(150) NOT NULL,
    FARM_NAME VARCHAR(150) NOT NULL,
    CITY VARCHAR(150),
    STATE VARCHAR(150),
    TOTAL_AREA NUMERIC(10,2),
    ARABLE_AREA NUMERIC(10,2),
    VEGETATION_AREA NUMERIC(10,2),
    PRIMARY KEY (PRODUCER_ID),
    CONSTRAINT FK_PRODUCER_DOCUMENT_TYPE FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES BRAIN_AGRICULTURE.DOCUMENT_TYPE (DOCUMENT_TYPE_ID)
);

INSERT INTO BRAIN_AGRICULTURE.PRODUCER (DOCUMENT_TYPE_ID, DOCUMENT_NUMBER, PRODUCER_NAME, FARM_NAME, CITY, STATE, TOTAL_AREA, ARABLE_AREA, VEGETATION_AREA) VALUES
(
    (SELECT DOCUMENT_TYPE_ID FROM BRAIN_AGRICULTURE.DOCUMENT_TYPE WHERE DOCUMENT_NAME = 'CPF'),
    '999.999.999-99',
    'TINNOVA',
    'TINNOVA-FARM',
    'SÃO JOSÉ DOS CAMPOS',
    'SÃO PAULO',
    100.00,
    25.25,
    10.05
);

CREATE TABLE BRAIN_AGRICULTURE.PRODUCER_PLANTED_CROPS (
    PRODUCER_PLANTED_CROP_ID INT DEFAULT nextval('BRAIN_AGRICULTURE.PRODUCER_PLANTED_CROPS_ID_SEQ') NOT NULL,
    PRODUCER_ID INT NOT NULL,
    PLANTED_CROP_ID INT NOT NULL,
    PRIMARY KEY (PRODUCER_PLANTED_CROP_ID),
    CONSTRAINT FK_PROD_PLANTED_CROPS_PROD FOREIGN KEY (PRODUCER_ID) REFERENCES BRAIN_AGRICULTURE.PRODUCER (PRODUCER_ID),
    CONSTRAINT FK_PROD_PLANTED_CROPS_PC FOREIGN KEY (PLANTED_CROP_ID) REFERENCES BRAIN_AGRICULTURE.PLANTED_CROPS (PLANTED_CROP_ID)
);

INSERT INTO BRAIN_AGRICULTURE.PRODUCER_PLANTED_CROPS (PRODUCER_ID, PLANTED_CROP_ID) VALUES
(
    (SELECT PRODUCER_ID FROM BRAIN_AGRICULTURE.PRODUCER WHERE PRODUCER_NAME = 'TINNOVA'),
    (SELECT PLANTED_CROP_ID FROM BRAIN_AGRICULTURE.PLANTED_CROPS WHERE PLANTED_CROP_NAME = 'Soja')
),
(
    (SELECT PRODUCER_ID FROM BRAIN_AGRICULTURE.PRODUCER WHERE PRODUCER_NAME = 'TINNOVA'),
    (SELECT PLANTED_CROP_ID FROM BRAIN_AGRICULTURE.PLANTED_CROPS WHERE PLANTED_CROP_NAME = 'Milho')
);
